In [3]:
import numpy as np

In [30]:
#
data=np.random.randn(2,3)
print(data)

# equql to range
data=np.arange(10)
print(data)

# astype,變更資料型態
arr=np.array([1,2,3,4])
print(arr.dtype)
print(arr)

float_arr=arr.astype('float64')
print(float_arr.dtype)
print(float_arr)

# list也可以轉換為數值
str_arr=np.array(['1.6','3.3','42'],dtype=np.string_)
str_arr.astype(float)
print(str_arr)


[[-0.30031936 -1.25818258 -1.44258551]
 [-1.11912974 -0.77122436 -0.48218948]]
[0 1 2 3 4 5 6 7 8 9]
int32
[1 2 3 4]
float64
[1. 2. 3. 4.]
[b'1.6' b'3.3' b'42']


In [47]:
# 多維度陣列
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)
print(arr3d.shape)
print(arr3d[0])
print(arr3d[0][1][1])

backup=arr3d.copy()
arr3d[0][0]=100
print(arr3d)

# 還原
arr3d=backup
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[1 2 3]
 [4 5 6]]
5
[[[100 100 100]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
